services:
  - type: web
    name: ericdigi-bot
    env: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"
    plan: free
