services:
  - type: web
    name: ericdigi-bot
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
    plan: free